[build]
  publish = "dist"
  command = "npm ci && npm run build:prod"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 