[build]
  publish = "dist"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 